meta_product_name: "MangeToo"
meta_title: "MangeToo - trust where you eat"
meta_description: "The essential little black book for globetrotting foodies"
meta_image: "MangeToo_MangeTooImage.png" # should exist in `app/assets/images/`
